source:
  type: http-json
  params:
    url: https://jsonplaceholder.typicode.com/users

transform:
  mapping:
    id: id
    nome: name
    email: email

destinations:
  - type: csv
    params:
      path: out/dados.csv
  - type: json
    params:
      path: out/dados.json
